//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RenewedApartmentThingy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentRentee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApartmentRentee()
        {
            this.ApartmentStatusTrails = new HashSet<ApartmentStatusTrail>();
        }
    
        public long ApartmentRenteeID { get; set; }
        public string ApartmentRenteeName { get; set; }
        public string ApartmentRenteeNumber { get; set; }
        public string ApartmentRenterIDNumber { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApartmentStatusTrail> ApartmentStatusTrails { get; set; }
    }
}
