//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RenewedApartmentThingy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentStatusTrail
    {
        public int ApartmentStatusTrailID { get; set; }
        public long ApartmentID { get; set; }
        public long ApartmentRenteeID { get; set; }
        public long AgentInvolved { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual ApartmentRentee ApartmentRentee { get; set; }
        public virtual Apartment Apartment { get; set; }
    }
}
