//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RenewedApartmentThingy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public long PhotoID { get; set; }
        public string PhotoName { get; set; }
        public long ApartmentID { get; set; }
        public string PhotoSection { get; set; }
    
        public virtual Apartment Apartment { get; set; }
    }
}
